### ISSUE TITLE
Automatically detect Language Packs

### ISSUE THREAD

**Issue by TheIsmy64** [Krummers/Intermezzo-Patcher#16]
Detect a `patch[Language].tar` automatically, without the need to rename the file to `patch2.tar` manually. Also, add a message confirming that the language you're about to use is the one you expect it to be. This should be an addition to the already existing `patch2.tar` detector, and one should take priority over the other, or a menu should be created to let the user select which `patchX.tar` they want to use as their `patch2.tar`.

Example: if there's  a `patchN.tar` it would say something like:
> A `patch2.tar` language pack has been detected with language: **Dutch**. Should this one be used? (Y/N):

If Y, it should rename the `patch[Language].tar` to `patch2.tar` automatically and proceed.
If N, it should just ignore the file and proceed.

**Comment by Exorcism0666** [comment]
patchBaguette.tar

**Comment by Krummers** [comment]
In addition, also recognise for which distribution the patch2.tar was made. This way mispatching does not happen anymore.

**Comment by Krummers** [comment]
This has now been implemented. Verifying the patch2.tar has been moved to #17 .
