### ISSUE TITLE
Automatically install required modules

### ISSUE THREAD

**Issue by Krummers** [Krummers/Intermezzo-Patcher#8]

**Comment by Krummers** [comment]
Thanks for the tip! I implemented it :)

**Comment by Lami-Lemmy** [comment]
Hardcoding it to be `pip install` might cause it to fail in the case where the user does not have pip added to PATH (I know I have it like that)

**Comment by Krummers** [comment]
Why would one remove it from path manually when installing Python adds it automatically?

**Comment by Lami-Lemmy** [comment]
It wasn't added automatically for me, cause I never removed it.

Also, in the case where the user has more than one python installation (i.e. multiple versions, alternate interpreters) then `pip` might not even correspond to the same python installation currently running.
